# Generated by Django 5.0.6 on 2024-07-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=50, null=True)),
                ('Category', models.CharField(max_length=50)),
                ('SubCategory', models.CharField(max_length=50, null=True)),
                ('ProductType', models.CharField(max_length=50, null=True)),
                ('Colour', models.CharField(max_length=50)),
                ('Usage', models.CharField(max_length=50, null=True)),
                ('ProductTitle', models.CharField(max_length=50)),
                ('ImageURL', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
