# Generated by Django 5.0.6 on 2024-07-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Usage',
        ),
    ]
